export const themeMapping = {
    light: {
        background: "white",
        text: "gray.800",
        button: "teal.500",
        buttonText: "white",
    },
    dark: {
        background: "gray.900",
        text: "white",
        button: "teal.300",
        buttonText: "black",
    },
    cupcake: {
        background: "pink.100",
        text: "gray.800",
        button: "pink.500",
        buttonText: "white",
    },
    bumblebee: {
        background: "yellow.100",
        text: "gray.800",
        button: "yellow.500",
        buttonText: "black",
    },
    emerald: {
        background: "green.100",
        text: "gray.800",
        button: "green.500",
        buttonText: "white",
    },
    corporate: {
        background: "blue.100",
        text: "gray.800",
        button: "blue.500",
        buttonText: "white",
    },
    synthwave: {
        background: "purple.800",
        text: "white",
        button: "purple.500",
        buttonText: "white",
    },
    retro: {
        background: "orange.600",
        text: "white",
        button: "orange.300",
        buttonText: "black",
    },
    cyberpunk: {
        background: "pink.800",
        text: "white",
        button: "cyan.400",
        buttonText: "black",
    },
    valentine: {
        background: "purple.200",
        text: "gray.800",
        button: "red.400",
        buttonText: "white",
    },
    halloween: {
        background: "purple.800",
        text: "green.400",
        button: "orange.600",
        buttonText: "green.400",
    },
    garden: {
        background: "green.300",
        text: "gray.800",
        button: "green.700",
        buttonText: "white",
    },
    forest: {
        background: "green.700",
        text: "green.300",
        button: "green.600",
        buttonText: "green.300",
    },
    aqua: {
        background: "cyan.500",
        text: "yellow.500",
        button: "blue.600",
        buttonText: "yellow.500",
    },
    lofi: {
        background: "gray.200",
        text: "blue.300",
        button: "cyan.500",
        buttonText: "blue.300",
    },
    pastel: {
        background: "pink.100",
        text: "blue.500",
        button: "blue.300",
        buttonText: "white",
    },
    fantasy: {
        background: "blue.300",
        text: "orange.300",
        button: "orange.500",
        buttonText: "white",
    },
    wireframe: {
        background: "gray.100",
        text: "gray.400",
        button: "gray.600",
        buttonText: "white",
    },
    black: {
        background: "black",
        text: "gray.300",
        button: "gray.700",
        buttonText: "gray.300",
    },
    luxury: {
        background: "gray.900",
        text: "gold.300",
        button: "gold.700",
        buttonText: "black",
    },
    dracula: {
        background: "gray.800",
        text: "red.300",
        button: "purple.600",
        buttonText: "red.300",
    },
    cmyk: {
        background: "cyan.200",
        text: "blue.300",
        button: "cyan.500",
        buttonText: "blue.300",
    },
    autumn: {
        background: "red.500",
        text: "orange.500",
        button: "orange.700",
        buttonText: "orange.500",
    },
    business: {
        background: "blue.100",
        text: "orange.200",
        button: "orange.600",
        buttonText: "orange.200",
    },
    acid: {
        background: "green.300",
        text: "yellow.400",
        button: "yellow.600",
        buttonText: "yellow.400",
    },
    lemonade: {
        background: "yellow.200",
        text: "orange.300",
        button: "orange.500",
        buttonText: "orange.300",
    },
    night: {
        background: "gray.800",
        text: "blue.400",
        button: "cyan.500",
        buttonText: "blue.400",
    },
    coffee: {
        background: "brown.200",
        text: "brown.700",
        button: "brown.500",
        buttonText: "brown.700",
    },
    winter: {
        background: "blue.200",
        text: "blue.400",
        button: "blue.500",
        buttonText: "blue.400",
    },
    dim: {
        background: "gray.600",
        text: "gray.300",
        button: "gray.500",
        buttonText: "gray.300",
    },
    nord: {
        background: "gray.700",
        text: "blue.200",
        button: "blue.600",
        buttonText: "blue.200",
    },
    sunset: {
        background: "orange.300",
        text: "blue.200",
        button: "blue.500",
        buttonText: "blue.200",
    },
};
